-- 120 NEW CHALLENGES
INSERT INTO challenges (id, title, description, category_id, difficulty, xp_reward, motivation_text, recurrence) VALUES

-- MIND & LEARNING (MND) - 20 challenges
(gen_random_uuid(), 'Learn a New Word', 'Learn and use a new word in conversation today.', (SELECT id FROM categories WHERE code='MND'), 1, 15, 'Expand your vocabulary one word at a time', 'daily'),
(gen_random_uuid(), 'Solve a Puzzle', 'Complete a crossword, Sudoku, or brain teaser.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Challenge your brain to stay sharp', 'daily'),
(gen_random_uuid(), 'Speed Reading Practice', 'Read 10 pages within 15 minutes.', (SELECT id FROM categories WHERE code='MND'), 3, 35, 'Read faster, learn more', 'daily'),
(gen_random_uuid(), 'Digital Detox Hour', 'Spend one hour without screens for focused learning.', (SELECT id FROM categories WHERE code='MND'), 3, 40, 'Unplug to reconnect with deep learning', 'daily'),
(gen_random_uuid(), 'Language Practice', 'Practice a foreign language for 15 minutes.', (SELECT id FROM categories WHERE code='MND'), 2, 30, 'New languages open new worlds', 'daily'),
(gen_random_uuid(), 'Summarize an Article', 'Read an article and write a 3-sentence summary.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Understanding comes from synthesis', 'daily'),
(gen_random_uuid(), 'Memory Palace', 'Use memory techniques to remember 5 new facts.', (SELECT id FROM categories WHERE code='MND'), 4, 50, 'Ancient techniques for modern minds', 'daily'),
(gen_random_uuid(), 'Critical Thinking Exercise', 'Analyze a news story from multiple perspectives.', (SELECT id FROM categories WHERE code='MND'), 3, 35, 'Think deeper, understand better', 'daily'),
(gen_random_uuid(), 'Learn a Shortcut', 'Master one keyboard shortcut or productivity hack.', (SELECT id FROM categories WHERE code='MND'), 1, 15, 'Work smarter, not harder', 'daily'),
(gen_random_uuid(), 'Book Chapter Analysis', 'Analyze one chapter of a book you are reading.', (SELECT id FROM categories WHERE code='MND'), 4, 45, 'Deep reading leads to deep understanding', 'daily'),
(gen_random_uuid(), 'Teach Something', 'Explain a concept you know to someone else.', (SELECT id FROM categories WHERE code='MND'), 3, 40, 'Teaching is learning twice', 'daily'),
(gen_random_uuid(), 'Speed Calculation', 'Practice mental math for 10 minutes.', (SELECT id FROM categories WHERE code='MND'), 2, 30, 'Keep your mind calculatingly sharp', 'daily'),
(gen_random_uuid(), 'Learn a Historical Fact', 'Research and remember one historical event.', (SELECT id FROM categories WHERE code='MND'), 1, 20, 'Today is tomorrow''s history', 'daily'),
(gen_random_uuid(), 'Scientific Method Practice', 'Apply scientific thinking to a daily observation.', (SELECT id FROM categories WHERE code='MND'), 3, 35, 'Curiosity fuels discovery', 'daily'),
(gen_random_uuid(), 'Listen to a Podcast', 'Listen to an educational podcast episode.', (SELECT id FROM categories WHERE code='MND'), 1, 20, 'Learn while you listen', 'daily'),
(gen_random_uuid(), 'Debate Practice', 'Form arguments for both sides of a simple topic.', (SELECT id FROM categories WHERE code='MND'), 4, 50, 'Understanding all sides makes you wiser', 'daily'),
(gen_random_uuid(), 'Speed Typing', 'Practice typing for 10 minutes to improve speed.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Words flow faster when fingers fly', 'daily'),
(gen_random_uuid(), 'Learn from Failure', 'Analyze one mistake and what you learned.', (SELECT id FROM categories WHERE code='MND'), 2, 30, 'Every failure is a lesson in disguise', 'daily'),
(gen_random_uuid(), 'Concept Mapping', 'Create a mind map for a complex topic.', (SELECT id FROM categories WHERE code='MND'), 3, 40, 'Visualize connections, deepen understanding', 'daily'),
(gen_random_uuid(), 'Daily Reflection', 'Write 3 things you learned today.', (SELECT id FROM categories WHERE code='MND'), 1, 20, 'Reflection turns experience into wisdom', 'daily'),

-- BODY & HEALTH (HLT) - 20 challenges
(gen_random_uuid(), 'Posture Check', 'Maintain good posture for 30 minutes straight.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Straight back, strong mind', 'daily'),
(gen_random_uuid(), 'Stair Master', 'Take the stairs instead of elevator all day.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Every step builds strength', 'daily'),
(gen_random_uuid(), 'Morning Sunlight', 'Get 10 minutes of morning sunlight exposure.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Sunshine fuels body and soul', 'daily'),
(gen_random_uuid(), 'Plank Challenge', 'Hold a plank for 60 seconds.', (SELECT id FROM categories WHERE code='HLT'), 3, 35, 'Core strength is total strength', 'daily'),
(gen_random_uuid(), 'Digital Eye Break', 'Take a 5-minute eye break every hour of screen time.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Rest your eyes to see farther', 'daily'),
(gen_random_uuid(), 'Balanced Meal', 'Eat a perfectly balanced meal with protein, veggies, and carbs.', (SELECT id FROM categories WHERE code='HLT'), 2, 30, 'Fuel your body right', 'daily'),
(gen_random_uuid(), 'Sleep Hygiene', 'Follow a consistent bedtime routine tonight.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Good sleep is the foundation of health', 'daily'),
(gen_random_uuid(), 'Full Body Stretch', 'Do a 15-minute full body stretching routine.', (SELECT id FROM categories WHERE code='HLT'), 2, 30, 'Flexibility is freedom', 'daily'),
(gen_random_uuid(), 'Breath Holding', 'Practice controlled breathing and hold for 30 seconds.', (SELECT id FROM categories WHERE code='HLT'), 1, 20, 'Control your breath, control your energy', 'daily'),
(gen_random_uuid(), 'No Sugar Day', 'Avoid added sugars for the entire day.', (SELECT id FROM categories WHERE code='HLT'), 3, 40, 'Sweetness comes from health, not sugar', 'daily'),
(gen_random_uuid(), 'Hydration Tracking', 'Track and meet your water intake goal.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Water is life''s elixir', 'daily'),
(gen_random_uuid(), 'Active Commute', 'Walk or bike for at least part of your commute.', (SELECT id FROM categories WHERE code='HLT'), 2, 30, 'Turn travel into training', 'daily'),
(gen_random_uuid(), 'Post-Workout Recovery', 'Do proper cool-down exercises after physical activity.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Recovery is part of the workout', 'daily'),
(gen_random_uuid(), 'Fruit Rainbow', 'Eat fruits of 3 different colors today.', (SELECT id FROM categories WHERE code='HLT'), 1, 20, 'Colorful plate, healthy body', 'daily'),
(gen_random_uuid(), 'Standing Desk Hour', 'Stand while working for at least one hour.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Stand up for your health', 'daily'),
(gen_random_uuid(), 'Heart Health', 'Do 20 minutes of cardio exercise.', (SELECT id FROM categories WHERE code='HLT'), 3, 35, 'A strong heart beats for a long life', 'daily'),
(gen_random_uuid(), 'Mindful Eating', 'Eat one meal without distractions, savoring each bite.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Food tastes better with attention', 'daily'),
(gen_random_uuid(), 'Digital Sunset', 'Turn off screens 1 hour before bedtime.', (SELECT id FROM categories WHERE code='HLT'), 2, 30, 'Darkness brings deep sleep', 'daily'),
(gen_random_uuid(), 'Posture Corrector', 'Set hourly reminders to check and correct posture.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Good posture becomes habit', 'daily'),
(gen_random_uuid(), 'Full Body Scan', 'Do a 5-minute body awareness meditation.', (SELECT id FROM categories WHERE code='HLT'), 1, 20, 'Listen to what your body needs', 'daily'),

-- KINDNESS & EMPATHY (EMP) - 20 challenges
(gen_random_uuid(), 'Thank You Notes', 'Write 3 thank you notes (digital or physical).', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Gratitude expressed is happiness doubled', 'daily'),
(gen_random_uuid(), 'Active Listening', 'Have a conversation where you only listen and ask questions.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'Sometimes the kindest thing is to listen', 'daily'),
(gen_random_uuid(), 'Pay It Forward', 'Do something nice for someone without expecting anything back.', (SELECT id FROM categories WHERE code='EMP'), 2, 30, 'Kindness creates ripples', 'daily'),
(gen_random_uuid(), 'Secret Good Deed', 'Do a good deed anonymously.', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Pure kindness needs no recognition', 'daily'),
(gen_random_uuid(), 'Compliment Chain', 'Give compliments to 3 different people.', (SELECT id FROM categories WHERE code='EMP'), 1, 20, 'Spread positivity like sunshine', 'daily'),
(gen_random_uuid(), 'Empathy Exercise', 'Imagine a day in someone else''s shoes.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'Understanding begins with imagination', 'daily'),
(gen_random_uuid(), 'Social Media Positivity', 'Leave only positive comments online today.', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Make the digital world kinder', 'daily'),
(gen_random_uuid(), 'Family Connection', 'Reach out to a family member you haven''t spoken to recently.', (SELECT id FROM categories WHERE code='EMP'), 2, 30, 'Family roots run deep', 'daily'),
(gen_random_uuid(), 'Service with a Smile', 'Perform a service task with extra warmth.', (SELECT id FROM categories WHERE code='EMP'), 1, 15, 'A smile is the universal welcome', 'daily'),
(gen_random_uuid(), 'Forgiveness Practice', 'Practice forgiving someone (including yourself).', (SELECT id FROM categories WHERE code='EMP'), 4, 45, 'Forgiveness sets everyone free', 'daily'),
(gen_random_uuid(), 'Support a Stranger', 'Help a stranger with a small task.', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Strangers are just friends you haven''t met', 'daily'),
(gen_random_uuid(), 'Emotional Check-in', 'Ask 3 people how they are really feeling.', (SELECT id FROM categories WHERE code='EMP'), 2, 30, 'Care is asking twice', 'daily'),
(gen_random_uuid(), 'Patience Practice', 'Practice extra patience in a frustrating situation.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'Patience is kindness to yourself and others', 'daily'),
(gen_random_uuid(), 'Community Support', 'Support a local business or community project.', (SELECT id FROM categories WHERE code='EMP'), 2, 30, 'Strong communities are built on support', 'daily'),
(gen_random_uuid(), 'Encouragement Spread', 'Encourage someone pursuing a goal.', (SELECT id FROM categories WHERE code='EMP'), 1, 20, 'Your belief can fuel someone''s dreams', 'daily'),
(gen_random_uuid(), 'Apology When Needed', 'Apologize sincerely if you''ve wronged someone.', (SELECT id FROM categories WHERE code='EMP'), 3, 40, 'Sorry mends what words break', 'daily'),
(gen_random_uuid(), 'Celebrate Others', 'Celebrate someone else''s achievement genuinely.', (SELECT id FROM categories WHERE code='EMP'), 1, 15, 'Joy shared is joy multiplied', 'daily'),
(gen_random_uuid(), 'Inclusive Language', 'Use inclusive language in all conversations.', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Words can include or exclude—choose wisely', 'daily'),
(gen_random_uuid(), 'Volunteer Time', 'Spend 30 minutes volunteering (in person or virtually).', (SELECT id FROM categories WHERE code='EMP'), 3, 40, 'Time is the most precious gift', 'daily'),
(gen_random_uuid(), 'Emotional First Aid', 'Offer comfort to someone having a hard day.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'Sometimes comfort is the best medicine', 'daily'),

-- MINDFULNESS & MENTAL WELLNESS (MMW) - 20 challenges
(gen_random_uuid(), 'Digital Mindfulness', 'Check notifications only at designated times today.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Control your attention, control your mind', 'daily'),
(gen_random_uuid(), 'Nature Connection', 'Spend 15 minutes in nature without distractions.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Nature is the original meditation', 'daily'),
(gen_random_uuid(), 'Single-Tasking', 'Focus on one task at a time for 2 hours.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'One thing at a time is enough', 'daily'),
(gen_random_uuid(), 'Emotion Labeling', 'Name and acknowledge 5 emotions you feel today.', (SELECT id FROM categories WHERE code='MMW'), 1, 20, 'Name it to tame it', 'daily'),
(gen_random_uuid(), 'Mindful Walking', 'Take a 10-minute walk paying attention to each step.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Walk as if you are kissing the earth with your feet', 'daily'),
(gen_random_uuid(), 'Digital Declutter', 'Organize your digital workspace for clarity.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Clear digital space, clear mind', 'daily'),
(gen_random_uuid(), 'Stress Scan', 'Notice physical signs of stress and release tension.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Awareness is the first step to release', 'daily'),
(gen_random_uuid(), 'Mindful Eating', 'Eat one meal in complete silence, savoring flavors.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'Silence makes taste brighter', 'daily'),
(gen_random_uuid(), 'Thought Detachment', 'Observe thoughts without judgment for 10 minutes.', (SELECT id FROM categories WHERE code='MMW'), 4, 45, 'You are not your thoughts', 'daily'),
(gen_random_uuid(), 'Sensory Grounding', 'Use 5-4-3-2-1 technique to ground yourself.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Ground yourself to soar higher', 'daily'),
(gen_random_uuid(), 'Mindful Waiting', 'Practice mindfulness during waiting times.', (SELECT id FROM categories WHERE code='MMW'), 1, 15, 'Waiting is not wasted time', 'daily'),
(gen_random_uuid(), 'Digital Boundaries', 'Set and respect one new digital boundary.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Boundaries create freedom', 'daily'),
(gen_random_uuid(), 'Body Scan Meditation', 'Do a full body scan meditation for 15 minutes.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'Your body holds wisdom—listen', 'daily'),
(gen_random_uuid(), 'Mindful Communication', 'Pause 3 seconds before responding in conversations.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Space between stimulus and response is freedom', 'daily'),
(gen_random_uuid(), 'Acceptance Practice', 'Practice accepting something you cannot change.', (SELECT id FROM categories WHERE code='MMW'), 4, 50, 'Acceptance is peace with reality', 'daily'),
(gen_random_uuid(), 'Mindful Transition', 'Create mindful transitions between activities.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Transitions are opportunities for presence', 'daily'),
(gen_random_uuid(), 'Gratitude Walk', 'Take a walk while listing things you are grateful for.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Walk with gratitude, arrive with joy', 'daily'),
(gen_random_uuid(), 'Digital Sabbath', 'Take 4 hours completely offline.', (SELECT id FROM categories WHERE code='MMW'), 3, 40, 'Disconnect to reconnect', 'daily'),
(gen_random_uuid(), 'Mindful Breathing Spaces', 'Take 3 one-minute breathing breaks today.', (SELECT id FROM categories WHERE code='MMW'), 1, 20, 'Breathe between moments', 'daily'),
(gen_random_uuid(), 'Self-Compassion Break', 'Give yourself the kindness you''d give a friend.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'You deserve your own kindness too', 'daily'),

-- CREATIVITY & CURIOSITY (CRT) - 20 challenges
(gen_random_uuid(), 'Curiosity Walk', 'Take a walk looking for 10 things you''ve never noticed.', (SELECT id FROM categories WHERE code='CRT'), 1, 20, 'Wonder is seeing with fresh eyes', 'daily'),
(gen_random_uuid(), 'Creative Constraints', 'Create something using only 3 materials.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Limits breed creativity', 'daily'),
(gen_random_uuid(), 'Question Storm', 'Write 20 questions about anything.', (SELECT id FROM categories WHERE code='CRT'), 2, 25, 'Questions are the engine of discovery', 'daily'),
(gen_random_uuid(), 'Analog Creation', 'Create something without using digital tools.', (SELECT id FROM categories WHERE code='CRT'), 2, 30, 'Hands remember what screens forget', 'daily'),
(gen_random_uuid(), 'Creative Remix', 'Combine two unrelated ideas into something new.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Innovation lives at intersections', 'daily'),
(gen_random_uuid(), 'Photo Story', 'Take 3 photos that tell a story.', (SELECT id FROM categories WHERE code='CRT'), 2, 25, 'Every picture holds a thousand stories', 'daily'),
(gen_random_uuid(), 'Idea Capture', 'Capture 5 creative ideas throughout the day.', (SELECT id FROM categories WHERE code='CRT'), 1, 20, 'Ideas are butterflies—catch them gently', 'daily'),
(gen_random_uuid(), 'Creative Collaboration', 'Create something with someone else.', (SELECT id FROM categories WHERE code='CRT'), 3, 40, 'Two minds create more than double', 'daily'),
(gen_random_uuid(), 'Reverse Thinking', 'Solve a problem by thinking backwards.', (SELECT id FROM categories WHERE code='CRT'), 4, 45, 'Sometimes the way forward is backward', 'daily'),
(gen_random_uuid(), 'Micro-Skill Practice', 'Practice a creative skill for 15 minutes.', (SELECT id FROM categories WHERE code='CRT'), 2, 25, 'Small practice, big progress', 'daily'),
(gen_random_uuid(), 'Creative Journal', 'Keep a journal of creative thoughts and inspirations.', (SELECT id FROM categories WHERE code='CRT'), 1, 15, 'Ideas grow when they''re written down', 'daily'),
(gen_random_uuid(), 'Art Appreciation', 'Study and appreciate one work of art deeply.', (SELECT id FROM categories WHERE code='CRT'), 2, 25, 'Beauty understood is beauty created', 'daily'),
(gen_random_uuid(), 'Creative Problem Solving', 'Solve a daily problem in 3 creative ways.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Problems are opportunities in disguise', 'daily'),
(gen_random_uuid(), 'Inspiration Collection', 'Collect 5 things that inspire you today.', (SELECT id FROM categories WHERE code='CRT'), 1, 20, 'Inspiration is everywhere for those who look', 'daily'),
(gen_random_uuid(), 'Creative Ritual', 'Establish a 10-minute daily creative ritual.', (SELECT id FROM categories WHERE code='CRT'), 2, 25, 'Rituals turn inspiration into creation', 'daily'),
(gen_random_uuid(), 'Cross-Disciplinary Learning', 'Learn one concept from an unrelated field.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'The best ideas cross boundaries', 'daily'),
(gen_random_uuid(), 'Creative Courage', 'Share a creative work with someone.', (SELECT id FROM categories WHERE code='CRT'), 4, 50, 'Creation shared is creation completed', 'daily'),
(gen_random_uuid(), 'Improvisation Practice', 'Improvise a solution to a small challenge.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Life is improvisation—practice makes perfect', 'daily'),
(gen_random_uuid(), 'Creative Rest', 'Take a break specifically to fuel creativity.', (SELECT id FROM categories WHERE code='CRT'), 1, 15, 'Rest is where creativity regenerates', 'daily'),
(gen_random_uuid(), 'Idea Incubation', 'Sleep on a creative problem and note morning insights.', (SELECT id FROM categories WHERE code='CRT'), 2, 30, 'The unconscious mind solves while you sleep', 'daily'),

-- ENVIRONMENT & RESPONSIBILITY (ENV) - 20 challenges
(gen_random_uuid(), 'Zero-Waste Meal', 'Prepare and eat a meal with no disposable packaging.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'Less waste, more taste', 'daily'),
(gen_random_uuid(), 'Energy Audit', 'Turn off all unnecessary electronics for 2 hours.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Conscious consumption starts with awareness', 'daily'),
(gen_random_uuid(), 'Sustainable Transport', 'Use public transport, bike, or walk for all trips.', (SELECT id FROM categories WHERE code='ENV'), 3, 40, 'Every green journey counts', 'daily'),
(gen_random_uuid(), 'Water Conservation', 'Reduce water usage by 20% today.', (SELECT id FROM categories WHERE code='ENV'), 2, 30, 'Every drop saved is a drop earned', 'daily'),
(gen_random_uuid(), 'Local Food Day', 'Eat only locally sourced food today.', (SELECT id FROM categories WHERE code='ENV'), 4, 50, 'Local food, global impact', 'daily'),
(gen_random_uuid(), 'Digital Cleanup', 'Delete unnecessary digital files to save energy.', (SELECT id FROM categories WHERE code='ENV'), 1, 15, 'Clean digital space, cleaner planet', 'daily'),
(gen_random_uuid(), 'Clothing Care', 'Repair or repurpose one item of clothing.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Love your clothes longer', 'daily'),
(gen_random_uuid(), 'Meatless Day', 'Go vegetarian or vegan for the entire day.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'Plants for the planet', 'daily'),
(gen_random_uuid(), 'Bulk Buying', 'Purchase one item in bulk to reduce packaging.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Buy in bulk, waste in small', 'daily'),
(gen_random_uuid(), 'Compost Practice', 'Properly compost all food waste today.', (SELECT id FROM categories WHERE code='ENV'), 2, 30, 'Waste to wealth, through compost', 'daily'),
(gen_random_uuid(), 'Eco-Friendly Cleaning', 'Use only natural cleaning products today.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Clean home, clean planet', 'daily'),
(gen_random_uuid(), 'Paperless Day', 'Avoid using any paper products.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'Save trees, save tomorrow', 'daily'),
(gen_random_uuid(), 'Energy Peak Avoidance', 'Use major appliances during off-peak hours.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Smart timing, smarter energy use', 'daily'),
(gen_random_uuid(), 'Reusable Everything', 'Use only reusable containers and bags.', (SELECT id FROM categories WHERE code='ENV'), 3, 40, 'Reuse is the highest form of recycling', 'daily'),
(gen_random_uuid(), 'Garden Care', 'Spend 15 minutes caring for plants or a garden.', (SELECT id FROM categories WHERE code='ENV'), 1, 20, 'Nurture nature, nurture yourself', 'daily'),
(gen_random_uuid(), 'Eco-Education', 'Learn one new fact about environmental protection.', (SELECT id FROM categories WHERE code='ENV'), 1, 15, 'Knowledge fuels action', 'daily'),
(gen_random_uuid(), 'Minimalist Challenge', 'Remove 5 unnecessary items from your space.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Less stuff, more freedom', 'daily'),
(gen_random_uuid(), 'Sustainable Shopping', 'Research the sustainability of one product before buying.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Every purchase is a vote for the future', 'daily'),
(gen_random_uuid(), 'Climate Conversation', 'Have a positive conversation about climate action.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'Change begins with conversation', 'daily'),
(gen_random_uuid(), 'Environmental Advocacy', 'Take one small action to support environmental policy.', (SELECT id FROM categories WHERE code='ENV'), 4, 50, 'Small actions create big movements', 'daily');
