-- 120 MORE NEW CHALLENGES
INSERT INTO challenges (id, title, description, category_id, difficulty, xp_reward, motivation_text, recurrence) VALUES

-- MIND & LEARNING (MND) - 20 more challenges
(gen_random_uuid(), 'Speed Learning', 'Learn one new concept in under 10 minutes.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Fast learning, lasting knowledge', 'daily'),
(gen_random_uuid(), 'Cognitive Reframe', 'Reframe one negative thought into a learning opportunity.', (SELECT id FROM categories WHERE code='MND'), 3, 35, 'Every challenge teaches something new', 'daily'),
(gen_random_uuid(), 'Pattern Recognition', 'Identify 5 patterns in your daily environment.', (SELECT id FROM categories WHERE code='MND'), 2, 30, 'Patterns reveal hidden connections', 'daily'),
(gen_random_uuid(), 'Knowledge Sharing', 'Share something you learned with a colleague or friend.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Shared knowledge grows exponentially', 'daily'),
(gen_random_uuid(), 'Memory Recall', 'Recall what you learned yesterday without notes.', (SELECT id FROM categories WHERE code='MND'), 2, 30, 'Recall strengthens memory', 'daily'),
(gen_random_uuid(), 'Analogy Creation', 'Create an analogy to explain a complex concept.', (SELECT id FROM categories WHERE code='MND'), 3, 40, 'Good analogies bridge understanding', 'daily'),
(gen_random_uuid(), 'Learning Sprint', 'Study intensively for 25 minutes without breaks.', (SELECT id FROM categories WHERE code='MND'), 3, 35, 'Focus creates flow', 'daily'),
(gen_random_uuid(), 'Crossword Completion', 'Complete a crossword puzzle or similar word game.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Words are windows to wisdom', 'daily'),
(gen_random_uuid(), 'Documentary Learning', 'Watch an educational documentary segment.', (SELECT id FROM categories WHERE code='MND'), 1, 20, 'Visual learning, deep understanding', 'daily'),
(gen_random_uuid(), 'Learning Application', 'Apply something you learned to a real situation.', (SELECT id FROM categories WHERE code='MND'), 4, 45, 'Applied knowledge is true knowledge', 'daily'),
(gen_random_uuid(), 'Cognitive Flexibility', 'Approach a problem from 3 different angles.', (SELECT id FROM categories WHERE code='MND'), 4, 50, 'Flexible thinking finds solutions', 'daily'),
(gen_random_uuid(), 'Information Synthesis', 'Combine information from 2 different sources.', (SELECT id FROM categories WHERE code='MND'), 3, 40, 'Synthesis creates new understanding', 'daily'),
(gen_random_uuid(), 'Learning Journal', 'Write about what you learned in a journal.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Writing solidifies learning', 'daily'),
(gen_random_uuid(), 'Expert Interview', 'Listen to an interview with an expert in any field.', (SELECT id FROM categories WHERE code='MND'), 1, 15, 'Learn from those who know', 'daily'),
(gen_random_uuid(), 'Mental Calculation', 'Do all simple math in your head today.', (SELECT id FROM categories WHERE code='MND'), 2, 30, 'Mental math keeps your brain sharp', 'daily'),
(gen_random_uuid(), 'Learning Chain', 'Connect today''s learning to something you already know.', (SELECT id FROM categories WHERE code='MND'), 3, 35, 'Connected knowledge sticks better', 'daily'),
(gen_random_uuid(), 'Information Evaluation', 'Critically evaluate one piece of information you receive.', (SELECT id FROM categories WHERE code='MND'), 3, 40, 'Critical thinking is self-defense for the mind', 'daily'),
(gen_random_uuid(), 'Learning Ritual', 'Establish a consistent time for daily learning.', (SELECT id FROM categories WHERE code='MND'), 2, 25, 'Rituals turn intentions into habits', 'daily'),
(gen_random_uuid(), 'Cognitive Warm-up', 'Do 5 minutes of brain exercises in the morning.', (SELECT id FROM categories WHERE code='MND'), 1, 15, 'Warm minds work better', 'daily'),
(gen_random_uuid(), 'Knowledge Gap', 'Identify and research one gap in your knowledge.', (SELECT id FROM categories WHERE code='MND'), 3, 35, 'Knowing what you don''t know is wisdom', 'daily'),

-- BODY & HEALTH (HLT) - 20 more challenges
(gen_random_uuid(), 'Hydration First', 'Drink a glass of water before your morning coffee.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Hydrate before you caffeinate', 'daily'),
(gen_random_uuid(), 'Posture Reset', 'Reset your posture every 30 minutes while sitting.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Posture resets lead to better alignment', 'daily'),
(gen_random_uuid(), 'Full Breath Practice', 'Take 10 full, deep breaths whenever you feel stressed.', (SELECT id FROM categories WHERE code='HLT'), 1, 20, 'Breath is the remote control for your nervous system', 'daily'),
(gen_random_uuid(), 'Nutrition Label Reading', 'Read and understand 3 nutrition labels today.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Know what fuels your body', 'daily'),
(gen_random_uuid(), 'Active Recovery', 'Do light movement on your rest days.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Active recovery speeds healing', 'daily'),
(gen_random_uuid(), 'Sleep Tracking', 'Track your sleep patterns and duration.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Knowledge about sleep improves sleep', 'daily'),
(gen_random_uuid(), 'Flexibility Test', 'Test and gently improve your flexibility.', (SELECT id FROM categories WHERE code='HLT'), 2, 30, 'Flexible body, flexible mind', 'daily'),
(gen_random_uuid(), 'Health Check-in', 'Check in with how your body feels throughout the day.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Listen to your body''s whispers', 'daily'),
(gen_random_uuid(), 'Movement Snacks', 'Do 5-minute movement breaks every 90 minutes.', (SELECT id FROM categories WHERE code='HLT'), 1, 20, 'Small movements, big benefits', 'daily'),
(gen_random_uuid(), 'Healthy Swap', 'Make one healthy food swap today.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Small swaps lead to big changes', 'daily'),
(gen_random_uuid(), 'Post-Exercise Nutrition', 'Eat proper nutrition within 45 minutes of exercise.', (SELECT id FROM categories WHERE code='HLT'), 2, 30, 'Refuel to rebuild', 'daily'),
(gen_random_uuid(), 'Digital Detox Movement', 'Move without any digital devices for 30 minutes.', (SELECT id FROM categories WHERE code='HLT'), 3, 35, 'Movement should be device-free', 'daily'),
(gen_random_uuid(), 'Balance Practice', 'Practice balance exercises for 5 minutes.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Balance in body creates balance in life', 'daily'),
(gen_random_uuid(), 'Joint Mobility', 'Do joint mobility exercises for all major joints.', (SELECT id FROM categories WHERE code='HLT'), 2, 30, 'Mobile joints, vibrant life', 'daily'),
(gen_random_uuid(), 'Restorative Yoga', 'Do 15 minutes of gentle, restorative yoga.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Restoration is as important as exertion', 'daily'),
(gen_random_uuid(), 'Vitamin D Boost', 'Get 15 minutes of midday sun exposure.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Sunshine is nature''s vitamin', 'daily'),
(gen_random_uuid(), 'Food Preparation', 'Prepare one healthy meal from scratch.', (SELECT id FROM categories WHERE code='HLT'), 3, 35, 'Prepared food is healthy food', 'daily'),
(gen_random_uuid(), 'Posture Awareness', 'Notice and correct your posture in different positions.', (SELECT id FROM categories WHERE code='HLT'), 2, 25, 'Awareness precedes correction', 'daily'),
(gen_random_uuid(), 'Cardio Variety', 'Try a new form of cardio exercise.', (SELECT id FROM categories WHERE code='HLT'), 3, 40, 'Variety prevents plateaus', 'daily'),
(gen_random_uuid(), 'Health Education', 'Learn one new fact about human health.', (SELECT id FROM categories WHERE code='HLT'), 1, 15, 'Knowledge empowers health choices', 'daily'),

-- KINDNESS & EMPATHY (EMP) - 20 more challenges
(gen_random_uuid(), 'Silent Support', 'Support someone without saying anything.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'Presence speaks louder than words', 'daily'),
(gen_random_uuid(), 'Compliment Diary', 'Write down compliments you receive today.', (SELECT id FROM categories WHERE code='EMP'), 1, 15, 'Good words deserve remembering', 'daily'),
(gen_random_uuid(), 'Empathy Stretch', 'Try to understand someone very different from you.', (SELECT id FROM categories WHERE code='EMP'), 4, 45, 'Growth happens outside comfort zones', 'daily'),
(gen_random_uuid(), 'Kindness Ripple', 'Do something kind that might inspire others to be kind.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'Kindness creates waves', 'daily'),
(gen_random_uuid(), 'Service Mindset', 'Look for opportunities to serve all day.', (SELECT id FROM categories WHERE code='EMP'), 2, 30, 'Service is the rent we pay for living', 'daily'),
(gen_random_uuid(), 'Listening Without Solving', 'Listen to someone without trying to fix their problem.', (SELECT id FROM categories WHERE code='EMP'), 3, 40, 'Sometimes listening is the solution', 'daily'),
(gen_random_uuid(), 'Gratitude Expression', 'Express specific gratitude to someone.', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Specific gratitude has more impact', 'daily'),
(gen_random_uuid(), 'Invisible Help', 'Help someone who will never know it was you.', (SELECT id FROM categories WHERE code='EMP'), 4, 50, 'True kindness seeks no reward', 'daily'),
(gen_random_uuid(), 'Patience Test', 'Practice extra patience in a long line or wait.', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Patience practiced is patience gained', 'daily'),
(gen_random_uuid(), 'Compassionate Boundary', 'Set a boundary with kindness and respect.', (SELECT id FROM categories WHERE code='EMP'), 4, 45, 'Boundaries can be bridges when set with love', 'daily'),
(gen_random_uuid(), 'Community Observation', 'Notice and appreciate community helpers.', (SELECT id FROM categories WHERE code='EMP'), 1, 15, 'Appreciation builds community', 'daily'),
(gen_random_uuid(), 'Random Connection', 'Have a genuine conversation with a stranger.', (SELECT id FROM categories WHERE code='EMP'), 3, 40, 'Strangers are just unmet friends', 'daily'),
(gen_random_uuid(), 'Emotional First Responder', 'Be the first to reach out when someone seems down.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'First responders save emotional lives', 'daily'),
(gen_random_uuid(), 'Kindness to Self', 'Do something unusually kind for yourself.', (SELECT id FROM categories WHERE code='EMP'), 2, 30, 'You can''t pour from an empty cup', 'daily'),
(gen_random_uuid(), 'Conflict De-escalation', 'De-escalate a potential conflict with kindness.', (SELECT id FROM categories WHERE code='EMP'), 4, 55, 'Kindness cools heated moments', 'daily'),
(gen_random_uuid(), 'Appreciation Circle', 'Appreciate 3 people in your immediate circle.', (SELECT id FROM categories WHERE code='EMP'), 1, 20, 'Appreciation strengthens bonds', 'daily'),
(gen_random_uuid(), 'Social Media Kindness', 'Post something positive and supportive online.', (SELECT id FROM categories WHERE code='EMP'), 2, 25, 'Fill feeds with kindness', 'daily'),
(gen_random_uuid(), 'Empathy Journal', 'Write about a situation from someone else''s perspective.', (SELECT id FROM categories WHERE code='EMP'), 3, 35, 'Writing walks in others'' shoes', 'daily'),
(gen_random_uuid(), 'Service Without Recognition', 'Do a service task that won''t be noticed.', (SELECT id FROM categories WHERE code='EMP'), 3, 40, 'The best service is invisible', 'daily'),
(gen_random_uuid(), 'Compassionate Correction', 'Correct someone with empathy and care.', (SELECT id FROM categories WHERE code='EMP'), 4, 50, 'Correction with compassion builds up', 'daily'),

-- MINDFULNESS & MENTAL WELLNESS (MMW) - 20 more challenges
(gen_random_uuid(), 'Mindful Morning', 'Start your day with 5 minutes of silent mindfulness.', (SELECT id FROM categories WHERE code='MMW'), 1, 20, 'How you start determines how you continue', 'daily'),
(gen_random_uuid(), 'Thought Weather', 'Observe thoughts like passing weather without attachment.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'Thoughts are weather, you are the sky', 'daily'),
(gen_random_uuid(), 'Digital Intention', 'Set an intention before using any digital device.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Intentional use prevents mindless scrolling', 'daily'),
(gen_random_uuid(), 'Sensory Awareness', 'Spend 5 minutes focusing only on one sense.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'One sense at a time reveals miracles', 'daily'),
(gen_random_uuid(), 'Mindful Transition', 'Create a 1-minute ritual between work and home.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Transitions deserve attention', 'daily'),
(gen_random_uuid(), 'Emotional Surfing', 'Ride an emotional wave without reacting immediately.', (SELECT id FROM categories WHERE code='MMW'), 4, 45, 'You can surf emotions instead of drowning', 'daily'),
(gen_random_uuid(), 'Mindful Consumption', 'Consume media with full attention and awareness.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'What you consume consumes you', 'daily'),
(gen_random_uuid(), 'Breath Anchor', 'Use your breath as an anchor throughout the day.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Breath is always with you', 'daily'),
(gen_random_uuid(), 'Digital Minimalism', 'Remove one unnecessary app or notification.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Digital minimalism creates mental space', 'daily'),
(gen_random_uuid(), 'Mindful Waiting', 'Practice mindfulness instead of impatience while waiting.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Waiting is meditation in disguise', 'daily'),
(gen_random_uuid(), 'Stress Signal Recognition', 'Notice early signs of stress in your body.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Early awareness prevents escalation', 'daily'),
(gen_random_uuid(), 'Mindful Listening', 'Listen to music with complete attention.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Music heard mindfully is medicine', 'daily'),
(gen_random_uuid(), 'Digital Sabbath Preparation', 'Prepare for a digital-free period.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Preparation ensures successful disconnection', 'daily'),
(gen_random_uuid(), 'Mindful Movement', 'Do one movement activity with full awareness.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'Movement with awareness is meditation', 'daily'),
(gen_random_uuid(), 'Thought Labeling', 'Label thoughts as "planning", "remembering", "worrying", etc.', (SELECT id FROM categories WHERE code='MMW'), 3, 40, 'Labeling creates distance', 'daily'),
(gen_random_uuid(), 'Gratitude Meditation', 'Meditate specifically on things you''re grateful for.', (SELECT id FROM categories WHERE code='MMW'), 2, 25, 'Gratitude meditation multiplies blessings', 'daily'),
(gen_random_uuid(), 'Mindful Eating Check-in', 'Check hunger and fullness levels before and after eating.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Your body knows what it needs', 'daily'),
(gen_random_uuid(), 'Digital Sunset Ritual', 'Create a ritual for ending screen time each evening.', (SELECT id FROM categories WHERE code='MMW'), 3, 35, 'Rituals close digital doors', 'daily'),
(gen_random_uuid(), 'Mindful Response Delay', 'Wait 10 seconds before responding to anything upsetting.', (SELECT id FROM categories WHERE code='MMW'), 3, 40, 'Space between stimulus and response is freedom', 'daily'),
(gen_random_uuid(), 'Present Moment Returns', 'Return to the present moment 10 times today.', (SELECT id FROM categories WHERE code='MMW'), 2, 30, 'Each return strengthens presence', 'daily'),

-- CREATIVITY & CURIOSITY (CRT) - 20 more challenges
(gen_random_uuid(), 'Daily Wonder', 'Find something that fills you with wonder today.', (SELECT id FROM categories WHERE code='CRT'), 1, 15, 'Wonder is the beginning of wisdom', 'daily'),
(gen_random_uuid(), 'Creative Constraints Challenge', 'Create something with a severe limitation.', (SELECT id FROM categories WHERE code='CRT'), 4, 50, 'Limitations breed innovation', 'daily'),
(gen_random_uuid(), 'Cross-Domain Inspiration', 'Get inspiration from a field unrelated to yours.', (SELECT id FROM categories WHERE code='CRT'), 3, 40, 'Cross-pollination creates new species of ideas', 'daily'),
(gen_random_uuid(), 'Creative Recovery', 'Return to an abandoned creative project.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Unfinished projects await resurrection', 'daily'),
(gen_random_uuid(), 'Idea Crossbreeding', 'Combine two existing ideas into something new.', (SELECT id FROM categories WHERE code='CRT'), 3, 40, 'Ideas have sex and produce offspring', 'daily'),
(gen_random_uuid(), 'Creative Risk', 'Share a creative work that makes you vulnerable.', (SELECT id FROM categories WHERE code='CRT'), 4, 55, 'Vulnerability is the birthplace of innovation', 'daily'),
(gen_random_uuid(), 'Curiosity Conversation', 'Have a conversation driven purely by curiosity.', (SELECT id FROM categories WHERE code='CRT'), 2, 30, 'Curiosity conversations discover new worlds', 'daily'),
(gen_random_uuid(), 'Creative Routine Break', 'Break your normal creative routine intentionally.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Routine breaks reveal new paths', 'daily'),
(gen_random_uuid(), 'Idea Incubation Walk', 'Take a walk specifically to incubate an idea.', (SELECT id FROM categories WHERE code='CRT'), 2, 25, 'Walking stirs the creative soup', 'daily'),
(gen_random_uuid(), 'Creative Apprenticeship', 'Study and emulate a creative you admire.', (SELECT id FROM categories WHERE code='CRT'), 3, 40, 'Apprenticeship precedes mastery', 'daily'),
(gen_random_uuid(), 'Failure Analysis', 'Analyze a creative failure for lessons.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Failed creations teach more than successes', 'daily'),
(gen_random_uuid(), 'Creative Environment Design', 'Design your environment to spark creativity.', (SELECT id FROM categories WHERE code='CRT'), 2, 30, 'Environment shapes creation', 'daily'),
(gen_random_uuid(), 'Idea Evolution', 'Take an old idea and evolve it significantly.', (SELECT id FROM categories WHERE code='CRT'), 4, 45, 'Ideas evolve like species', 'daily'),
(gen_random_uuid(), 'Creative Meditation', 'Meditate on a creative problem or challenge.', (SELECT id FROM categories WHERE code='CRT'), 3, 40, 'Meditation clears creative blocks', 'daily'),
(gen_random_uuid(), 'Inspiration Collection', 'Collect physical objects that inspire you.', (SELECT id FROM categories WHERE code='CRT'), 1, 20, 'Physical inspiration anchors creative energy', 'daily'),
(gen_random_uuid(), 'Creative Collaboration Online', 'Collaborate creatively with someone online.', (SELECT id FROM categories WHERE code='CRT'), 3, 40, 'Digital collaboration breaks geographical barriers', 'daily'),
(gen_random_uuid(), 'Idea Speed Dating', 'Generate 10 ideas in 10 minutes.', (SELECT id FROM categories WHERE code='CRT'), 3, 35, 'Quantity leads to quality', 'daily'),
(gen_random_uuid(), 'Creative Teaching', 'Teach someone a creative skill you know.', (SELECT id FROM categories WHERE code='CRT'), 3, 40, 'Teaching creativity spreads creativity', 'daily'),
(gen_random_uuid(), 'Unusual Material Creation', 'Create something from unusual or found materials.', (SELECT id FROM categories WHERE code='CRT'), 4, 50, 'Unusual materials spark unusual ideas', 'daily'),
(gen_random_uuid(), 'Creative Documentation', 'Document your creative process for one project.', (SELECT id FROM categories WHERE code='CRT'), 2, 30, 'Documented processes become repeatable successes', 'daily'),

-- ENVIRONMENT & RESPONSIBILITY (ENV) - 20 more challenges
(gen_random_uuid(), 'Carbon Footprint Reduction', 'Make one choice to reduce your carbon footprint.', (SELECT id FROM categories WHERE code='ENV'), 2, 30, 'Small footprints leave big impressions', 'daily'),
(gen_random_uuid(), 'Sustainable Fashion Choice', 'Choose clothing with sustainability in mind.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'What you wear matters to the planet', 'daily'),
(gen_random_uuid(), 'Energy Efficient Day', 'Use only energy-efficient appliances and lighting.', (SELECT id FROM categories WHERE code='ENV'), 3, 40, 'Efficiency is environmentalism', 'daily'),
(gen_random_uuid(), 'Water Footprint Awareness', 'Calculate and reduce your water footprint.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'Every drop has a footprint', 'daily'),
(gen_random_uuid(), 'Plastic Audit', 'Track all plastic you use and discard today.', (SELECT id FROM categories WHERE code='ENV'), 2, 30, 'Awareness precedes reduction', 'daily'),
(gen_random_uuid(), 'Sustainable Transportation Day', 'Use only sustainable transportation methods.', (SELECT id FROM categories WHERE code='ENV'), 4, 50, 'Green travel is smart travel', 'daily'),
(gen_random_uuid(), 'Local Economy Support', 'Support a local business or farmer.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Local support builds resilient communities', 'daily'),
(gen_random_uuid(), 'Food Waste Reduction', 'Reduce your food waste by 50% today.', (SELECT id FROM categories WHERE code='ENV'), 3, 40, 'Wasted food is wasted resources', 'daily'),
(gen_random_uuid(), 'Eco-Friendly Personal Care', 'Use only eco-friendly personal care products.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'What goes on your body goes in the water', 'daily'),
(gen_random_uuid(), 'Sustainable Workspace', 'Make your workspace more environmentally friendly.', (SELECT id FROM categories WHERE code='ENV'), 2, 30, 'Green workspaces inspire green thinking', 'daily'),
(gen_random_uuid(), 'Environmental Advocacy Action', 'Take one action to support environmental causes.', (SELECT id FROM categories WHERE code='ENV'), 4, 50, 'Action speaks louder than concern', 'daily'),
(gen_random_uuid(), 'Circular Economy Practice', 'Repair, reuse, or repurpose something instead of discarding.', (SELECT id FROM categories WHERE code='ENV'), 3, 40, 'Circular economy mimics nature', 'daily'),
(gen_random_uuid(), 'Sustainable Investment', 'Make one sustainable investment or purchase decision.', (SELECT id FROM categories WHERE code='ENV'), 3, 35, 'Money talks—make it speak sustainability', 'daily'),
(gen_random_uuid(), 'Eco-Education Sharing', 'Share one environmental fact with someone.', (SELECT id FROM categories WHERE code='ENV'), 2, 25, 'Shared knowledge creates collective action', 'daily'),
(gen_random_uuid(), 'Zero-Waste Challenge', 'Produce no landfill waste today.', (SELECT id FROM categories WHERE code='ENV'), 4, 60, 'Zero waste is the ultimate goal', 'daily'),
(gen_random_uuid(), 'Sustainable Diet Day', 'Eat a completely sustainable diet today.', (SELECT id FROM categories WHERE code='ENV'), 4, 55, 'Every bite is a vote for the planet', 'daily'),
(gen_random_uuid(), 'Environmental Volunteer Hour', 'Volunteer for an environmental cause.', (SELECT id FROM categories WHERE code='ENV'), 3, 45, 'Hands-on help makes real difference', 'daily'),
(gen_random_uuid(), 'Green Technology Use', 'Use green technology in your daily life.', (SELECT id FROM categories WHERE code='ENV'), 3, 40, 'Technology can heal the planet', 'daily'),
(gen_random_uuid(), 'Sustainable Event Planning', 'Plan an event with sustainability in mind.', (SELECT id FROM categories WHERE code='ENV'), 4, 50, 'Celebrations should honor the earth', 'daily'),
(gen_random_uuid(), 'Environmental Mindfulness', 'Practice mindfulness of your environmental impact all day.', (SELECT id FROM categories WHERE code='ENV'), 3, 40, 'Mindful living is sustainable living', 'daily');