version: '3.8'

services:
  db:
    image: postgres:15
    container_name: strivexp-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strivexp-net

volumes:
  postgres_data:

networks:
  strivexp-net:
    driver: bridge

